#!/bin/bash

#
# Manages defaults: manages settings in RC files
#

awesome_pile_include messages


case "$SHELL" in
    *"/bash")
        AP_SH_RC="$HOME/.bashrc"
    ;;
    *"/zsh")
        AP_SH_RC="$HOME/.zshrc"
    ;;
    *)
        AP_SH_RC=""
    ;;
esac

ap_add_permanent_path(){
    if [ -n "$AP_SH_RC" ] && [ -f "$AP_SH_RC" ]; then
        grep -q "ap_add_path \"$@\"" "$AP_SH_RC"
        verbose_exit_code "Adding new path to $AP_SH_RC..."
        if [ $? -ne 0 ]; then
            echo "ap_add_path \"$@\"" >> "$AP_SH_RC"
        fi;
        
    fi
}

ap_add_path(){
    export PATH="$@:PATH"
}
