#!/bin/bash

#
# Manages defaults: manages settings in RC files
#

awesome_pile_include messages

case "$SHELL" in
    *"/bash")
        AWESOME_PILE_SH_RC="$HOME/.bashrc"
    ;;
    *"/zsh")
        AWESOME_PILE_SH_RC="$HOME/.zshrc"
    ;;
    *)
        AWESOME_PILE_SH_RC=""
    ;;
esac

awesome_pile_add_permanent_path(){
    if [ -n "$AWESOME_PILE_SH_RC" ] && [ -f "$AWESOME_PILE_SH_RC" ]; then
        grep -q "awesome_pile_add_path \"$@\"" "$AWESOME_PILE_SH_RC"
        if [ $? -ne 0 ]; then
            echo "awesome_pile_add_path \"$@\"" >> "$AWESOME_PILE_SH_RC"
        fi;
        grep -q "awesome_pile_add_path \"$@\"" "$AWESOME_PILE_SH_RC"
        verbose_exit_code "Adding new path to $AWESOME_PILE_SH_RC..."
        
    fi
}

awesome_pile_add_path(){
    export PATH="$@:PATH"
}
