#!/bin/bash

#
# Manages defaults: manages settings in RC files
#

awesome_shell_include messages

if [ -z "$BASH_VERSION" ];then
    AWESOME_SH_RC="$HOME/.bashrc";
elif [ -z "$ZSH_VERSION" ];then
    AWESOME_SH_RC="$HOME/.zshrc"
else
    AWESOME_SH_RC=""
fi;

awesome_shell_install(){
    if [ -n "$AWESOME_SH_RC" ] && [ -f "$AWESOME_SH_RC" ]; then
        echo -n "Installing Awesome Shell Scripts to $AWESOME_SH_RC..."
        local install_comment="# Awesome Shell scripts"
        grep -q "$install_comment" "$AWESOME_SH_RC"
        if [ $? -ne 0 ]; then
            echo >> "$AWESOME_SH_RC"
            echo "$install_comment" >> "$AWESOME_SH_RC"
            echo "if [ -x \"$awesome_shell_commons_file_dir/commons\" ];then" >> "$AWESOME_SH_RC"
            echo "    source \"$awesome_shell_commons_file_dir/commons\";" >> "$AWESOME_SH_RC"
            echo "fi;" >> "$AWESOME_SH_RC"
        fi;
        verbose_exit_code
    else
        fatal "Only Bash and Zsh are supported at the monent"
    fi;

}

awesome_shell_add_permanent_path(){
    if [ -n "$AWESOME_SH_RC" ] && [ -f "$AWESOME_SH_RC" ]; then
        grep -q "awesome_shell_add_path \"$@\"" "$AWESOME_SH_RC"
        if [ $? -ne 0 ]; then
            echo "awesome_shell_add_path \"$@\"" >> "$AWESOME_SH_RC"
        fi;
        grep -q "awesome_shell_add_path \"$@\"" "$AWESOME_SH_RC"
        verbose_exit_code "Adding new path to $AWESOME_SH_RC..."
        
    fi
}

awesome_shell_add_path(){
    export PATH="$@:PATH"
}
