#!/bin/bash

#
# Help module: add automatic agrument for help
# if help message is defined by user.
#
# Here is how to add help message:
# 
#
#   CURRENT_SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
#   awesome_pile_helpma <<_HELP_
#       Usage: $CURRENT_SCRIPT_NAME
#
#       Some message here that client will see if script is executed with
#       --help or -h switches
#
#   _HELP_


awesome_pile_include messages

awesome_pile_help(){
    read -d '' -t 3 AWESOME_PILE_HELP_MESSAGE
    [ -z "$AWESOME_PILE_HELP_MESSAGE" ] || awesome_pile_show_help_with_arg_check    
}

awesome_pile_show_help(){
    msg "$AWESOME_PILE_HELP_MESSAGE"
}


awesome_pile_show_help_with_arg_check(){
    for arg in "$awesome_pile_arguments"
    do
        case "$arg" in
          --help|-h)
            awesome_pile_show_help
            exit 0
          ;;
          *)
          ;;
        esac
    done
}

