#!/usr/bin/env bash

#
# Password module: functions for passwords and credentials
#

awesome_shell_include messages

# Keep sudo timestamp alive
keep_sudo_alive(){
    # ask for password
    sudo -v -p 'Enter sudo password [%p]:'
    if [ $? -eq 0 ];then
        # while both parent and current processes are running:
        while kill -0 "$PPID" && kill -0 "$$"; do
            sudo -n true
            sleep 30
        done 2>/dev/null &
    else
       fatal "Cannot get correct sudo password" 
    fi;
}
