#!/usr/bin/env bash

file="${BASH_SOURCE[0]:-$0}"
while [ -h "$file" ]; do # while source is a symlink
    dir="$( cd -P "$( dirname "$file" )" && pwd )"
    file="$(readlink "$file")"
    [[ "$file" != /* ]] && file="$dir/$file" # complete dir path for relative symlinks
done
dir="$( cd -P "$( dirname "$file" )" && pwd )"
          
if [ -x "$dir/commons" ]; then
    source "$dir/commons"
else
    echo "Cannot init awesome-shell commons"
    exit 1
fi

if [ -f "$1" ]; then
    awesome_shell_script_path="$1"
    awesome_shell_script_name=$(basename "$1")
    shift # so that the name of the script in no longer in $1 position
    awesome_shell_arguments=("${@:1}")
    script=$(cat "$awesome_shell_script_path")
    if [[ "$script" == *awesome_shell_help* ]];then
        awesome_shell_include help
    fi;
    eval "$script"
fi
