#!/usr/bin/env bash

export AWESOME_SHELL_REPO_DIR=$(cd "${BATS_TEST_DIRNAME}/.."; printf "$(pwd)")
export AWESOME_BASH="$AWESOME_SHELL_REPO_DIR/awesome-bash"
[[ "$PATH" = *"$AWESOME_SHELL_REPO_DIR"* ]] || export PATH="$AWESOME_SHELL_REPO_DIR:$PATH"
