#!/usr/bin/env bash

if [ -n "$BASH_VERSION" ];then
    _awesome_bash_completion(){
        local cur opts
        cur="${COMP_WORDS[COMP_CWORD]}"
        opts="--verbose --version --ref --update --list-libraries --generate-stub"
        COMPREPLY=($(compgen -W "$opts" -- "$cur"))
        return 0
    }

    complete -F _awesome_bash_completion awesome-bash
fi;